### PR TITLE
Format frontend, make API keys view prettier and add copy to clipboard functionality

### PR DESCRIPTION
**Pull request by sondr3**
I changed the design for the API keys view in the frontend to use the full width of the display if the screen is large enough and add two cards per row using `grid`:

image

And I also added a button and functionality to copy to clipboard for the keys, to make it easier to properly copy the key :shipit: 

image

And the PR is fairly large, mostly because I ran `npx prettier --write frontend` to format it 🙈

### CODE REVIEW

**Comment by matsbyfl** [comment]
Minor detail. Should the "Rotate key" button be set to type "fare" so that is gets a red color? 
I notice that I always want to click this button when it looks like a primary action. 

https://design.nav.no/designsystem/components/knapp

**Comment by sondr3** [comment]
Done! 😄

**Comment by x10an14** [comment]
Request I want to sneak in (doesn't need to be accepted): Could we by-default hide the keys? With something like `*****`?

So people sharing screens don't accidentally show all keys?

**Review by ambientsound — APPROVED** [review]
Good to merge.

**Comment by ambientsound** [comment]
> Request I want to sneak in (doesn't need to be accepted): Could we by-default hide the keys? With something like `*****`?
> 
> So people sharing screens don't accidentally show all keys?

Great suggestion, but out of scope for this PR.

**Pull request merged**
